services:
  - type: web
    name: face-service
    env: python
    region: oregon
    rootDir: face-service
    pythonVersion: 3.10.13
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
